#!/bin/bash

ZK_PATH="/Users/zubrik/projects/vaults"

cd $ZK_PATH

gstatus=`git status --porcelain`

if [ ${#gstatus} -ne 0 ]
then

  git add --all
  git commit -m "automated sync: $gstatus"
  git pull --rebase
  git push

fi